name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    strategy:
      matrix:
        compiler: ['lualatex', 'pdflatex']
        faculty: ['eiti', 'meil']
        lang: ['eng','pol']
        thesis: ['EngineerThesis', 'MasterThesis']
      fail-fast: false
    steps:
      - name: Checkout WUT-Thesis repository
        uses: actions/checkout@v2

      - name: Install LaTeX dependencies
        run: |
          sudo apt-get install -y   \
               biber                \
               latexmk              \
               python3-pip          \
               texlive              \
               texlive-bibtex-extra \
               texlive-fonts-extra  \
               texlive-latex-extra  \
               texlive-lang-polish  \
               texlive-luatex       \
               tex-gyre

      - name: Install Python dependencies
        run: sudo pip install -r requirements.txt

      - name: Build PDF file
        run: scons all